-- Inserts for symptom table
INSERT INTO symptom (dtype, id, isamental_illness, name) 
VALUES 
('Symptom', 1,  false, 'Nedostatak lične higijene'),
('Symptom', 2,  false, 'Poteškoće sa ustajanjem iz kreveta'),
('Symptom', 3,  false, 'Insomnija'),
('Symptom', 4,  false, 'Hipersomnija'),
('Symptom', 5,  false, 'Izbjegavanje socijalnih situacija'),
('Symptom', 6,  false, 'Znojenje'),
('Symptom', 7,  false, 'Crvenilo u licu'),
('Symptom', 8,  false, 'Drhtanje'),
('Symptom', 9,  false, 'Vizuelne halucinacije'),
('Symptom', 10, false, 'Auditorne halucinacije'),
('Symptom', 11, false, 'Alogija'),
('Symptom', 12, false, 'Paralogizmi'),
('Symptom', 13, false, 'Eholalija'),
('Symptom', 14, false, 'Inkoherentnost govora'),
('Symptom', 15, false, 'Osjećaj težine u tijelu'),
('Symptom', 16, false, 'Tromost'),
('Symptom', 17, false, 'Ubrzan rad srca'),
('Symptom', 18, false, 'Uznemirenost'),
('Symptom', 19, false, 'Strah'),
('Symptom', 20, false, 'Bezbrižnost'),
('Symptom', 21, false, 'Smanjen apetit'),
('Symptom', 22, false, 'Nedostatak motivacije'),
('Symptom', 23, false, 'Suicidalnost'),
('Symptom', 24, false, 'Smanjena koncentracija'),
('Symptom', 25, false, 'Povećana motivacija'),
('Symptom', 26, false, 'Manjak volje'),
('Symptom', 27, false, 'Halucinacije'),
('Symptom', 28, false, 'Strah od socijalnih situacija'),
('Symptom', 29, false, 'Problemi sa snom'),
('Symptom', 30, false, 'Anksioznost'),
('Symptom', 31, false, 'Manjak energije'),
('Symptom', 32, true,  'Socijalna anksioznost'),
('Symptom', 33, true,  'Depresivni poremećaj'),
('Symptom', 34, true,  'Briga');

-- Inserts for symptom_relationship table
INSERT INTO symptom_relationship (parent_symptom_id, child_symptom_id) 
VALUES 
(26, 1),
(26, 2),
(26, 16),
(26, 21),
(26, 22),
(27, 9),
(27, 10),
(28, 5),
(28, 6),
(28, 7),
(28, 17),
(29, 3),
(29, 4),
(30, 34),
(30, 19),
(30, 18),
(31, 2),
(31, 4),
(31, 15),
(31, 16),
(32, 28),
(32, 30),
(33, 26),
(33, 31),
(33, 29),
(33, 23),
(33, 24);
